language: minimal

addons:
  ssh_known_hosts: ibragimov.by

before_install:
  - export HUGO_VERSION=0.69.2
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb"
  - sudo dpkg -i "hugo_${HUGO_VERSION}_Linux-64bit.deb"

script:
  - hugo

branches:
  only:
    - master

deploy:
  provider: script
  script: bash .ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master

cache:
  yarn: true
