title: "Zero Entropy"
baseURL: "https://ruslan.ibragimov.by/"
languageCode: "en-us"
theme: irus
rssLimit: 10

DefaultContentLanguage: en
languages:
  en:
    weight: 1
    params:
      text: "Read in english"
  ru:
    weight: 2
    params:
      text: "Read in russian"

permalinks:
  posts: /:year/:month/:day/:filename/

preserveTaxonomyNames: true

markup:
  highlight:
    noClasses: false
