name: "Build"
on:
  push:
    branches:
      - main
jobs:
  build:
    name: "Build on Ubuntu"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Create LFS file list"
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: "Restore LFS cache"
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
      - name: "Git LFS Pull"
        run: git lfs pull
      - name: "Setup Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.83.1"
        run: hugo
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Login to GHCR"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password:  ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push"
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ghcr.io/irus/blog:main
