name: "Build"
on:
  push:
    branches:
      - main
jobs:
  build:
    name: "Build on Ubuntu"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Create LFS file list"
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: "Restore LFS cache"
        uses: actions/cache@v4
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
      - name: "Git LFS Pull"
        run: git lfs pull
      - name: "Setup Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.122.0"
      - run: hugo
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Login to GHCR"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          tags: ghcr.io/irus/blog:main
